### ISSUE TITLE
Add support for Linux 32 bits?

### ISSUE THREAD

**Issue by gsmet** [bit3/jsass#11]
Hi,

We still have 32 bits Linux dev machines here and there and I was wondering if jsass could easily support 32 bits Linux?

I'm willing to do the leg work if it seems feasible and a pull request implementing that would be accepted.

Thanks for the feedback!
## 

Guillaume

**Comment by tristanlins** [comment]
hey @gsmet, in the latest development release, I have renamed the `build-linux` docker container into `build-linux-x64`. I am open to it to merge even a Linux 32 container pull request. :-)
At the moment I'm working on windows 32bit and 64bit builds.

**Comment by tristanlins** [comment]
I take a look around. The main problem why 32bit architecture is not supported is, that docker officially only support 64bit. But there are some 32bit docker images on the hub, like [32bit/ubuntu](https://hub.docker.com/r/32bit/ubuntu/), [f69m/ubuntu32](https://hub.docker.com/r/f69m/ubuntu32/) or [phusion/centos-5-32](https://hub.docker.com/r/phusion/centos-5-32/).
It may be possible to create a 32bit [build container](https://github.com/bit3/jsass/tree/master/src/main/docker/build-linux-x64) with them.

**Comment by gsmet** [comment]
Yes, I started to work on this with a CentOS 5 32 bits image.

**Comment by tristanlins** [comment]
:+1:

**Comment by ern** [comment]
Would also like to see a linux x86 version as well.

**Comment by Poeschl** [comment]
Any progress on this?

**Comment by tristanlins** [comment]
Not that I know of ¯\_(ツ)_/¯

**Comment by tristanlins** [comment]
I have started on a 32bit build in the [feature-linux-x32](https://github.com/bit3/jsass/tree/feature-linux-x32) feature branch.
Inexplicably the unit tests are failing with class not found errors.
I will continue the work within the next days.

**Comment by tristanlins** [comment]
I'm happy to announce, that 32bit support will come soon. I have [merged](https://github.com/bit3/jsass/commit/f8a02d7a0540618b04bd2fe6bba3f3a0cf5d3f64) the feature-linux-x32 branch.
After playing around, finally a 32bit library can be build within a 32bit centos docker container.
Before making the release, I need to do some maintenance work. The travis builds failing, because the new docker containers are still missing on docker hub. But this should all be done in less than an hour.
I'm optimistic that tomorrow night the new version will arrive ;-)

**Comment by Poeschl** [comment]
Wow that was fast :+1: Thanks for your effort.

**Comment by tristanlins** [comment]
[Version 5.5](https://github.com/bit3/jsass/releases/tag/5.5.0) is released now. 👏

**Comment by Poeschl** [comment]
Nice
