### ISSUE TITLE
Lost track of Import context

### ISSUE THREAD

**Issue by gsmet** [bit3/jsass#12]
Hi,

I'm trying to use the Importer machinery to be able to load files from the classpath (and optionally load files from other parts of the classpath using scopes).

I tried something like this: https://github.com/gsmet/jsass-test , it's a simple Maven project with a self contained test case. It looks like somehow jsass lost track of the context of the previous import when it tries to import the test/test2 file. It seems to me the previous import should still have the long classpath uri as its base uri.

Any pointers on how to solve this issue?

Thanks!

**Comment by gsmet** [comment]
Hi Tristan,

I worked around it by keeping track of the previous import directly in my JSassScopeAwareImporter.

That said, I still think there's something fishy and what I tried should work out of the box.

**Comment by gsmet** [comment]
Yeah well, it works in this example but doesn't work on more complex ones as I don't have the import stack.

**Comment by tristanlins** [comment]
Hi, I haven't the time yet to take a look at the problem. But your workaround may work for simple use cases. But you cannot correctly track the previous import when you get into a chain of imports.
But you're absolutely right, this should work out of the box :-)

**Comment by tristanlins** [comment]
I take a look into the problem. It seems that the problem lays in libsass, not jsass.
The libsass function `sass_import_get_base` (expected: `classpath:/fr/openwide/jsass/test/resource/_test.scss`, actual: `test`) return the same as `sass_import_get_path`, which is wrong.

The issues https://github.com/sass/libsass/issues/1035 and https://github.com/sass/libsass/issues/1041 describe this issue. This may be fixed in libsass 3.3 (which contains further API breaks...), but for the moment jsass 3 support only libsass 3.2.

You can work around by using an absolute import path and ignore the base.

```java
@Override
public Collection<Import> apply(String url, Import previous) {
  return Collections.singletonList(getInputSource(url, previous.getUri()));
}

public Import getInputSource(String url, URI base) {
  ...
  return new Import(potentialUri, null, source);
  ...
}
```

**Comment by tristanlins** [comment]
For the moment I added a unit test in the branch `hotfix-issue-12` that covers your problem with a minimal example.

**Comment by gsmet** [comment]
Hi Tristan,

I suspected an issue with libsass as I couldn't find the bug in jsass.

Thanks for the workaround, I got it working.
